mutation CreateTipoCosto($input: TipoCostoRequest!) {
  createTipoCosto(input: $input) {
    id
  }
}

mutation CreateBodega($input: BodegaRequest!) {
  createBodega(input: $input) {
    id
  }
}

mutation CreateConteoCiclico($input: ConteoCiclicoRequest!) {
  createConteoCiclico(input: $input) {
    id
  }
}

mutation CreateCostoOrden($input: CostoOrdenRequest!) {
  createCostoOrden(input: $input) {
    id
  }
}

mutation CreateDiscrepanciaInventario($input: DiscrepanciaInventarioRequest!) {
  createDiscrepanciaInventario(input: $input) {
    id
  }
}

mutation CreateEstacionProduccion($input: EstacionProduccionRequest!) {
  createEstacionProduccion(input: $input) {
    id
  }
}

mutation CreateEstadoOrden($input: EstadoOrdenRequest!) {
  createEstadoOrden(input: $input) {
    id
  }
}

mutation CreateInventarioLote($input: InventarioLoteRequest!) {
  createInventarioLote(input: $input) {
    id
  }
}

mutation CreateLineaOrden($input: LineaOrdenRequest!) {
  createLineaOrden(input: $input) {
    id
  }
}

mutation CreateLoteProduccion($input: LoteProduccionRequest!) {
  createLoteProduccion(input: $input) {
    id
  }
}

mutation CreateMetodoValoracion($input: MetodoValoracionRequest!) {
  createMetodoValoracion(input: $input) {
    id
  }
}

mutation CreateMovimientoInventarioDetalle(
  $input: MovimientoInventarioDetalleRequest!
) {
  createMovimientoInventarioDetalle(input: $input) {
    id
  }
}

mutation CreateMovimientoInventario($input: MovimientoInventarioRequest!) {
  createMovimientoInventario(input: $input) {
    id
  }
}

mutation CreateOrdenEstacion($input: OrdenEstacionRequest!) {
  createOrdenEstacion(input: $input) {
    id
  }
}

mutation CreateOrdenEvento($input: OrdenEventoRequest!) {
  createOrdenEvento(input: $input) {
    id
  }
}

mutation CreateOrdenProduccion($input: OrdenProduccionRequest!) {
  createOrdenProduccion(input: $input) {
    id
  }
}

mutation CreateProducto($input: ProductoRequest!) {
  createProducto(input: $input) {
    id
  }
}

mutation CreatePuntoReorden($input: PuntoReordenRequest!) {
  createPuntoReorden(input: $input) {
    id
  }
}

mutation CreateReservaMaterialOrden($input: ReservaMaterialOrdenRequest!) {
  createReservaMaterialOrden(input: $input) {
    id
  }
}

mutation CreateTipoBodega($input: TipoBodegaRequest!) {
  createTipoBodega(input: $input) {
    id
  }
}

mutation CreateTipoProducto($input: TipoProductoRequest!) {
  createTipoProducto(input: $input) {
    id
  }
}

mutation CreateUnidadConversion($input: UnidadConversionRequest!) {
  createUnidadConversion(input: $input) {
    id
  }
}

mutation CreateUnidadMedida($input: UnidadMedidaRequest!) {
  createUnidadMedida(input: $input) {
    id
  }
}

mutation CreateUnidadMedidaTipo($input: UnidadMedidaTipoRequest!) {
  createUnidadMedidaTipo(input: $input) {
    id
  }
}
